# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tts_app' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tts_app



  platform :ios, '9.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'


  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  target 'tts_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tts_app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tts_app-tvOS

  target 'tts_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
